#!/usr/bin/env bash
source ~/.cache/wal/colors.sh

rgb=$(echo $background | cut -c 2-)
rgb=$(bash ~/.config/scripts/hextorgb.sh $rgb)
#echo $rgb

r=$(echo $rgb | cut -d ' ' -f 1)
g=$(echo $rgb | cut -d ' ' -f 2)
b=$(echo $rgb | cut -d ' ' -f 3)

echo " # Config automatically generated by ~/.config/scripts/setTermiteConfig.sh

[options]
dynamic_title = true
font = Overpass Mono 10
scrollback_lines = 10000
hyperlinks = true
cursor_blink = system
cursor_shape = ibeam
scrollbar = right

[colors]
background = rgba($r, $g, $b, 0.9)
foreground = $foreground
cursor = $cursor

color0=$color0
color1=$color1
color2=$color2
color3=$color3
color4=$color4
color5=$color5
color6=$color6
color7=$color7
color8=$color8
color9=$color9
color10=$color10
color11=$color11
color12=$color12
color13=$color13
color14=$color14
color15=$color15" > ~/.config/termite/config
